### ISSUE TITLE
Support class-string type

### ISSUE THREAD

**Issue by MaXal** [JetBrains/phpstorm-psalm-plugin#13]
Code to reproduce:
```
<?php

/**
 * @param array<int, class-string<ProxyGeneratorInterface>|class-string> $arr
 */
function takesArray(array $arr): void
{
    if ($arr) {
        echo $arr[1]; // type should be string
    }
}

```

The highlighting is broken, type is not inferred as a string and there is no completion.

![image](https://user-images.githubusercontent.com/266747/86801686-98c4e000-c074-11ea-8314-bb9378d9a105.png)

**Comment by wbars** [comment]
Related changes in parser https://youtrack.jetbrains.com/issue/WI-54194
