### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by mr-feek** [JetBrains/phpstorm-psalm-plugin#38]
I just wanted to send an explicit thank you to the devs working on this plugin. I'm really excited and it's going to greatly improve my workflows!

**Comment by orklah** [comment]
I'm really hyped too. Reading the issues and seeing things being developped is really cool, I'm glad you decided to release this in Open Source.

Thanks a lot!

**Comment by wbars** [comment]
Thank you for the encouragement comments, please stay tuned :)
