### ISSUE TITLE
Psalm annotations and native stubs

### ISSUE THREAD

**Issue by orklah** [JetBrains/phpstorm-psalm-plugin#70]
Hi Folks,

Once again, thanks for this amazing project.

Is there any plan to migrate/specify [PhpStorm stubs](https://github.com/JetBrains/phpstorm-stubs) with the more precise annotations from psalm/phpstan?

If there's grunt work to be done, I'm sure people (including me) are ready to help !

**Comment by wbars** [comment]
Hello! Since PhpStorm stubs are designed to reflect current state of PHP core library and this plugin provides support for a 3rd party tool we don't consider merging them as current goal of any of these projects at current moment.
